404_message_1 = "The page you're looking for could not be found."
404_message_2 = "to return to the main page."
404_not_found = "404 Not Found"
activate = "Activate"
activation_success = "Account activated. You may now proceed to login to your account."
activation_validation_token = "Please provide a valid activation token"
admin = "Admin"
admin_dashboard = "Admin Dashboard"
click_here = "Click here"
created_by = "Created by"
dashboard_message = "You now have an authenticated session, feel free to log out using the link in the navbar above."
email_address = "Email address"
footer_message_1 = "Fork this project on"
forgot_password = "Forgot password?"
forgot_password_message = "Use the form below to reset your password. If we have an account with your email you will receive instructions on how to reset your password."
forgot_password_success = "An email with instructions describing how to reset your password has been sent."
home = "Home"
index_message_1 = "A simple website with user login and registration."
index_message_2 = "The frontend uses"
index_message_3 = "and the backend is written in"
index_message_4 = "Read more about this project on"
lang_key = "en"
login = "Login"
login_activated_error = "Account is not activated yet."
login_error = "Could not login, please make sure that you have typed in the correct email and password. If you have forgotten your password, please click the forgot password link below."
login_terms = "By pressing the button below to login you agree to the use of cookies on this website."
logout = "Logout"
no_results_found = "No results found"
password = "Password"
password_error = "Your password must be 8 characters in length or longer"
password_reset = "Password Reset"
password_reset_email = "Use the following link to reset your password. If this was not requested by you, please ignore this email.\n%s"
password_reset_success = "Your password has successfully been reset."
register = "Register"
register_error = "Could not register, please make sure the details you have provided are correct and that you do not already have an existing account."
register_success = "Thank you for registering. An activation email has been sent with steps describing how to activate your account."
request_activation_email = "Request activation email"
request_new_activation_email = "Request a new activation email"
request_reset_email = "Request reset email"
resend_activation_email = "Resend Activation Email"
resend_activation_email_message = "If you have already registered but never activated your account you can use the form below to request a new activation email."
resend_activation_email_subject = "Resend Activation Email"
resend_activation_email_success = "A new activation email has been sent if the account exists and is not already activated. Please remember to check your spam inbox in case the email is not showing in your inbox."
reset_password = "Reset Password"
reset_password_error = "Could not reset password, please try again"
reset_password_message = "Please enter a new password."
search = "Search"
search_results = "Search Results"
site_name = "Golang Base Project"
user_activation = "User Activation"
user_activation_email = "Use the following link to activate your account. If this was not requested by you, please ignore this email.\n%s"
